// ============================================================================
// DRIFTFIELD — RWS MAJOR ARCANA: CARDS II–XXI
// Core data for remaining 20 Majors. Full domain branches authored separately.
// Structure matches CardKnowledge — domains populated with foundational content.
// ============================================================================

import type { CardKnowledge, DomainInterpretation } from './types';

// Helper: generates a placeholder domain entry from upright/reversed summaries
function domainFrom(up: string, rev: string, adviceUp: string, adviceRev: string): DomainInterpretation {
  return {
    upright: { core: up, advice: adviceUp, warning: '', affirmation: '' },
    reversed: { core: rev, advice: adviceRev, warning: '', affirmation: '' }
  };
}

export const RWS_MAJORS_II_XXI: CardKnowledge[] = [

  // II — THE HIGH PRIESTESS
  {
    cardId: 'major-02', cardName: 'The High Priestess',
    coreMeaning: {
      upright: 'The answer is within you, but it speaks in silence. Intuition, the subconscious, and hidden knowledge are active. Stop looking outward and listen inward.',
      reversed: 'Disconnection from intuition. You are ignoring your inner voice, or the inner voice is obscured by noise, anxiety, or the opinions of others.'
    },
    keywords: { upright: ['intuition', 'mystery', 'subconscious', 'inner voice', 'stillness', 'wisdom'], reversed: ['secrets', 'disconnection', 'repressed intuition', 'information withheld', 'surface thinking', 'noise'] },
    domains: {
      love: domainFrom('A deeper layer of the relationship is trying to surface. Trust what you feel, not just what you see.', 'Emotional truth is being suppressed. Someone — possibly you — is hiding their real feelings.', 'Be still and listen. The relationship is telling you something important if you stop performing long enough to hear it.', 'What are you afraid to know? The truth you\'re avoiding is the truth that matters most.'),
      career: domainFrom('Important information is not yet visible. Wait before making major career decisions — something is about to be revealed.', 'You\'re making career decisions based on surface-level information. Dig deeper before committing.', 'Trust the quiet knowing. If something feels off about an opportunity, it probably is.', 'Stop gathering opinions and sit with what you already know. The answer is there.'),
      spiritual: domainFrom('Deep spiritual insight is available through contemplation and receptivity. This is the card of the mystic — the one who knows through being, not through seeking.', 'Spiritual disconnection through over-intellectualization or external noise. You\'re reading about meditation instead of meditating.', 'Practice stillness. The High Priestess teaches through silence, not through words.', 'Return to the practice that feeds your soul. Not the one that impresses others.'),
      health: domainFrom('Your body is sending subtle signals. Pay attention to the whispers before they become shouts.', 'Ignoring health intuitions or dismissing symptoms. Something needs attention that you\'ve been avoiding.', 'Listen to your body\'s quiet communications. That recurring discomfort has a message.', 'Check in with yourself. Sometimes the body knows before the conscious mind does.'),
      creative: domainFrom('Creative insight is arriving from the unconscious. Dreams, sudden ideas, and the feeling that something is trying to emerge through you — this is The High Priestess\'s domain.', 'Creative block caused by overthinking. You\'re trying to force what can only come through receptivity.', 'Stop trying to be creative and let creativity come to you. Make space. Be quiet. Wait.', 'Your creative work needs more dreaming and less planning right now.'),
      financial: domainFrom('Financial information is incomplete. Something about the numbers, the deal, or the opportunity is not yet visible. Wait for full disclosure.', 'You\'re making financial decisions without all the facts, or someone is withholding financial information.', 'Don\'t sign anything until the hidden information surfaces. Patience now saves money later.', 'Trust the instinct that says something doesn\'t add up. Run the numbers again.'),
      family: domainFrom('A family secret or unspoken truth is influencing dynamics. The High Priestess suggests that what\'s not being said is more important than what is.', 'Secrets within the family are creating disconnection. The unspoken is becoming toxic.', 'Create space for the truth to emerge. You can\'t force it, but you can make it safe.', 'Sometimes families need a quiet truth-teller more than they need a loud one.'),
      self: domainFrom('You know more than you think you know. The High Priestess in the self domain points to deep self-knowledge that is available through introspection rather than external validation.', 'You\'ve lost connection with your inner knowing. Too much external input has drowned out the internal signal.', 'Spend time alone. Not lonely alone — purposefully alone. The self speaks in solitude.', 'Your inner compass works. You just need to stop spinning long enough to read it.'),
      general: domainFrom('Hidden knowledge is present. The answer exists but is not yet visible to the conscious mind. Patience and receptivity will reveal what action cannot.', 'Secrets, repressed knowledge, or willful ignorance. Something important is being hidden or ignored.', 'Be patient. Not everything can be forced into the light. Some things emerge on their own schedule.', 'The information you need is coming. Trust the process of revelation.')
    },
    positions: {
      situation: { positionKey: 'situation', frame: 'The situation contains hidden dimensions. What you see is not the full picture.', emphasis: 'hidden knowledge' },
      challenge: { positionKey: 'challenge', frame: 'The challenge is patience — waiting for information that hasn\'t surfaced yet.', emphasis: 'the unseen' },
      advice: { positionKey: 'advice', frame: 'Trust your intuition. The rational mind doesn\'t have all the answers here.', emphasis: 'inner knowing' },
      outcome: { positionKey: 'outcome', frame: 'This leads to deeper understanding — but it arrives through revelation, not effort.', emphasis: 'illumination through patience' },
      hidden: { positionKey: 'hidden', frame: 'The hidden influence is your own intuition, which has been trying to tell you something you\'re not ready to hear.', emphasis: 'suppressed knowing' },
    },
    emotionalModifiers: {
      anxious: { toneShift: 'Anxiety clouds the intuitive channel. The High Priestess asks you to breathe, settle, and listen beneath the noise.', gentleOpening: 'The anxiety is loud, but beneath it, there\'s a quieter knowing. Can you hear it?' },
      grieving: { toneShift: 'In grief, The High Priestess holds space for what cannot be spoken. Some truths are felt, not said.', gentleOpening: 'Not everything about loss needs to be understood. Some of it just needs to be held.' },
    },
    interactions: [
      { otherCardId: 'major-01', relationship: 'opposed_by', description: 'The Magician acts; The High Priestess receives. Action vs. contemplation.', narrativeBridge: 'The tension between doing and being is central to this reading.' },
      { otherCardId: 'major-18', relationship: 'amplified_by', description: 'The Moon deepens The High Priestess\'s mystery into full confrontation with the unconscious.', narrativeBridge: 'The depths are speaking. This is not a time for surface understanding.' },
    ],
    fieldResponses: { positiveHigh: 'The field is receptive. Intuitive signals are amplified — trust what comes.', positiveMild: 'A gentle current supports inner knowing.', neutral: 'The field is still. Listen in the stillness.', negativeMild: 'Slight turbulence may cloud intuition. Ground yourself before interpreting.', negativeHigh: 'The field is agitated. Distinguishing intuition from anxiety requires extra care.' },
    correspondences: { element: 'water', planet: 'Moon', hebrewLetter: 'Gimel', numerology: 2, treeOfLifePath: 'Kether to Tiphareth', birthChartResonance: 'The Moon in your chart activates The High Priestess. Where your Moon sits natally, your intuitive and emotional intelligence runs deepest.' }
  },

  // III — THE EMPRESS
  {
    cardId: 'major-03', cardName: 'The Empress',
    coreMeaning: { upright: 'Abundance, fertility, and nurturing creative power. The Empress is the generative force — she creates life, beauty, and sustenance. Something is growing, and it needs tending.', reversed: 'Creative block, neglect of self or others, suffocating control disguised as care. The nurturing energy is either absent or overdone.' },
    keywords: { upright: ['abundance', 'fertility', 'nurturing', 'nature', 'beauty', 'sensuality', 'creation'], reversed: ['creative block', 'dependence', 'smothering', 'neglect', 'barrenness', 'disconnection from body'] },
    domains: {
      love: domainFrom('Love is fertile ground right now. Whether deepening an existing bond or cultivating a new one, the conditions favor growth, intimacy, and emotional abundance.', 'Love is being withheld, smothered, or neglected. Either you\'re not receiving enough nurture, or you\'re giving so much that you\'ve emptied yourself.', 'Tend the relationship as you would tend a garden. It needs consistent care, not grand gestures.', 'Ask yourself whether you\'re nurturing this connection or controlling it.'),
      career: domainFrom('A creative or nurturing career phase. Projects are bearing fruit. Collaborative, generative work environments thrive under this energy.', 'Creative stagnation at work. The environment may be hostile to growth, or you\'ve stopped investing creative energy into what you do.', 'Bring beauty and care to your work. Even practical work benefits from the creative touch.', 'If nothing is growing in this environment, the soil may be the problem, not the seeds.'),
      spiritual: domainFrom('Connection to the sacred through the body, nature, and the senses. The Empress\'s spirituality is embodied, not abstract.', 'Disconnection from the body and the natural world. Spirituality has become too cerebral.', 'Go outside. Touch the earth. Spirituality lives in the body.', 'Your spiritual practice needs more sensory engagement and less intellectual framework.'),
      health: domainFrom('The body is fertile ground for healing. Nutritional abundance, rest, and gentle care support recovery and vitality.', 'Neglecting the body\'s needs — poor nutrition, insufficient rest, or pushing through when rest is required.', 'Treat your body with the tenderness you\'d offer something precious. It is.', 'What does your body actually need right now? Not what you think it should need — what it\'s asking for.'),
      creative: domainFrom('Peak creative fertility. Ideas are abundant, the work flows, and the creative process feels natural and generative. This is the card of the artist in full bloom.', 'The muse has gone quiet, or creative output feels forced and lifeless. Something is blocking the natural flow of creative energy.', 'Create for the pleasure of creating. Let the work be alive before you worry about whether it\'s good.', 'If the creativity has dried up, you may be too far from the things that nourish you.'),
      financial: domainFrom('Financial abundance and the wisdom to enjoy it. Resources are available and should be appreciated, not hoarded.', 'Financial over-indulgence or the inability to enjoy what you have because of scarcity mindset.', 'Spend on what truly nourishes you. Abundance isn\'t about having more — it\'s about enjoying what you have.', 'Are you saving out of wisdom or out of fear? The Empress knows the difference.'),
      family: domainFrom('The nurturing center of the family is active. Maternal energy — from anyone, regardless of gender — is creating warmth and stability.', 'Family nurturing is absent or excessive. Either nobody is tending to emotional needs, or someone is smothering in the name of love.', 'Be the nurturing presence without losing yourself in the role.', 'Care for others from overflow, not from obligation.'),
      self: domainFrom('Self-care as a creative act. The Empress in the self domain says: you deserve to be tended, fed, rested, and delighted. This is not indulgence — it is foundation.', 'Self-neglect. You are giving to everyone except yourself, and the deficit is showing.', 'Put yourself on the list of things you take care of. At the top.', 'You cannot pour from an empty vessel. Fill yourself first.'),
      general: domainFrom('Growth, abundance, and creative fertility. Something is ready to bloom. The conditions are right.', 'Stagnation or excess. Either growth has stalled, or abundance has tipped into waste.', 'Nurture what matters. Let what doesn\'t matter fall away naturally.', 'The things that grow are the things that receive consistent, loving attention.')
    },
    positions: {
      situation: { positionKey: 'situation', frame: 'The situation is fertile. Something is growing and needs tending.', emphasis: 'growth and nurture' },
      advice: { positionKey: 'advice', frame: 'Nurture what matters. Apply care, patience, and beauty to the situation.', emphasis: 'creative cultivation' },
      outcome: { positionKey: 'outcome', frame: 'This leads to abundance — something beautiful and sustaining if properly tended.', emphasis: 'fruitful result' },
    },
    emotionalModifiers: {
      anxious: { toneShift: 'The Empress softens anxiety with the reminder that growth takes time. Not everything needs to be forced.', gentleOpening: 'Breathe. What\'s growing doesn\'t need your worry — it needs your care.' },
      grieving: { toneShift: 'In grief, The Empress is the mother who holds you. The card offers comfort rather than answers.', gentleOpening: 'You are allowed to be held. You are allowed to need tenderness.' },
    },
    interactions: [
      { otherCardId: 'major-04', relationship: 'opposed_by', description: 'The Emperor provides structure; The Empress provides nurture. Both are needed, but they pull in different directions.', narrativeBridge: 'The question here is balance: how much structure, and how much flow?' },
    ],
    fieldResponses: { positiveHigh: 'The field overflows with generative energy. Creation is strongly supported.', positiveMild: 'A warm current nourishes the reading. Growth is favored.', neutral: 'Balanced conditions for steady growth.', negativeMild: 'Growth faces mild headwinds. Extra nurturing effort needed.', negativeHigh: 'The field is depleted. Resources for growth may be scarce. Tend carefully.' },
    correspondences: { element: 'earth', planet: 'Venus', hebrewLetter: 'Daleth', numerology: 3, treeOfLifePath: 'Chokmah to Binah', birthChartResonance: 'Venus in your chart is activated by The Empress. Where Venus sits natally, your capacity for love, beauty, and creative abundance is strongest.' }
  },

  // IV–XXI: Core structure. Full domain branches to be authored.
  // Each entry below provides complete core meanings, keywords, correspondences,
  // and key position/field/interaction data. Domain branches follow the same
  // structure as The Fool/Magician/High Priestess/Empress above.

  ...[
    { id: 'major-04', name: 'The Emperor', up: 'Authority, structure, and the power to build lasting systems. The Emperor creates order from chaos — not through force alone, but through the discipline to maintain what he builds.', rev: 'Tyranny, rigidity, or the abdication of authority. Power misused, structure become prison, or the refusal to take responsibility for what you\'ve been given to steward.', kUp: ['authority','structure','discipline','stability','protection','leadership'], kRev: ['tyranny','rigidity','domination','inflexibility','control','absent father'], el: 'fire' as const, zod: 'Aries', heb: 'He', num: 4, path: 'Chokmah to Tiphareth', chart: 'Aries energy in your chart aligns with The Emperor. Where Mars and Aries sit natally, your capacity for decisive authority and disciplined action is strongest.' },

    { id: 'major-05', name: 'The Hierophant', up: 'Tradition, institutional wisdom, and the teacher who preserves and transmits knowledge. The Hierophant represents the structures through which wisdom is passed down — education, religion, mentorship, established practice.', rev: 'Dogma, blind conformity, or rejection of all tradition. Either slavish adherence to rules that have lost their meaning, or iconoclasm that throws away wisdom along with the institution.', kUp: ['tradition','conformity','education','spiritual wisdom','institution','mentorship'], kRev: ['dogma','restriction','challenging convention','unorthodoxy','hypocrisy','outdated beliefs'], el: 'earth' as const, zod: 'Taurus', heb: 'Vav', num: 5, path: 'Chokmah to Chesed', chart: 'Taurus energy in your chart resonates with The Hierophant. Where Taurus and Venus sit, your relationship with tradition and established knowledge is most active.' },

    { id: 'major-06', name: 'The Lovers', up: 'A profound choice, authentic connection, and the alignment of values. The Lovers is not simply about romance — it is about choosing what you truly value and committing to it fully, especially when that choice requires sacrifice.', rev: 'Misalignment of values, avoidance of a necessary choice, or a relationship built on a lie. Something fundamental is out of sync — either within you or between you and another.', kUp: ['love','harmony','partnership','values','choices','alignment'], kRev: ['disharmony','imbalance','misalignment','poor choices','infidelity','inner conflict'], el: 'air' as const, zod: 'Gemini', heb: 'Zayin', num: 6, path: 'Binah to Tiphareth', chart: 'Gemini energy in your chart activates The Lovers. Wherever Gemini sits, your capacity for choice, communication, and duality is most alive.' },

    { id: 'major-07', name: 'The Chariot', up: 'Victory through willpower and the integration of opposing forces. The Chariot moves forward not by eliminating conflict but by harnessing it — pulling both sides into a single direction through sheer determination.', rev: 'Loss of direction, aggression without strategy, or the inability to integrate competing drives. You\'re being pulled in two directions and neither side is winning.', kUp: ['victory','determination','willpower','control','assertion','momentum'], kRev: ['defeat','scattered energy','aggression','no direction','loss of control','internal conflict'], el: 'water' as const, zod: 'Cancer', heb: 'Cheth', num: 7, path: 'Binah to Geburah', chart: 'Cancer energy in your chart resonates with The Chariot. Where the Moon and Cancer sit natally, your emotional drive and protective determination are strongest.' },

    { id: 'major-08', name: 'Strength', up: 'Gentle power, courage that doesn\'t need to be loud, and the mastery of instinct through patience rather than force. The woman and the lion — the rational self and the animal self — in harmony, not domination.', rev: 'Insecurity, self-doubt, or the inability to control impulses. Either suppressing your nature so completely that you lose vitality, or being overwhelmed by appetites and reactions.', kUp: ['courage','patience','inner strength','compassion','influence','self-mastery'], kRev: ['self-doubt','weakness','insecurity','raw emotion','loss of nerve','overwhelm'], el: 'fire' as const, zod: 'Leo', heb: 'Teth', num: 8, path: 'Chesed to Geburah', chart: 'Leo in your chart is activated by Strength. Where the Sun and Leo sit natally, your capacity for courageous, generous self-expression is most alive.' },

    { id: 'major-09', name: 'The Hermit', up: 'Solitude as wisdom, not isolation. The Hermit withdraws from the world not to hide but to illuminate — carrying the lantern of hard-won understanding into the dark places where only the solitary can go.', rev: 'Isolation, withdrawal from life, or the refusal to share what you\'ve learned. Loneliness mistaken for wisdom, or wisdom hoarded instead of shared.', kUp: ['solitude','introspection','wisdom','guidance','soul-searching','inner light'], kRev: ['isolation','loneliness','withdrawal','paranoia','anti-social','lost'], el: 'earth' as const, zod: 'Virgo', heb: 'Yod', num: 9, path: 'Chesed to Tiphareth', chart: 'Virgo in your chart resonates with The Hermit. Where Mercury and Virgo sit natally, your capacity for discerning analysis and purposeful solitude is strongest.' },

    { id: 'major-10', name: 'Wheel of Fortune', up: 'The cycle turns. Change is coming — not through your action but through the natural rotation of fate. What was at the bottom rises; what was at the top descends. The only constant is the turning itself.', rev: 'Resistance to natural cycles, bad luck, or the feeling of being trapped on a wheel you can\'t escape. External forces are moving against you, or you\'re clinging to a phase that has already ended.', kUp: ['change','cycles','fate','destiny','turning point','luck','karma'], kRev: ['bad luck','resistance','stagnation','setbacks','unwelcome change','clinging'], el: 'fire' as const, planet: 'Jupiter', heb: 'Kaph', num: 10, path: 'Chesed to Netzach', chart: 'Jupiter in your chart is activated by the Wheel of Fortune. Where Jupiter sits natally, the cycles of expansion and contraction are most powerful in your life.' },

    { id: 'major-11', name: 'Justice', up: 'Truth, accountability, and the precise balance of cause and effect. Justice sees clearly and acts accordingly. What you have sown, you will reap — and the harvest is fair even when it doesn\'t feel kind.', rev: 'Injustice, dishonesty, or avoiding accountability. The scales are tipped — someone is not telling the truth, a decision is biased, or you\'re refusing to accept the consequences of your actions.', kUp: ['justice','truth','fairness','law','accountability','balance','consequence'], kRev: ['injustice','dishonesty','bias','avoiding accountability','unfairness','legal trouble'], el: 'air' as const, zod: 'Libra', heb: 'Lamed', num: 11, path: 'Geburah to Tiphareth', chart: 'Libra in your chart is activated by Justice. Where Venus and Libra sit natally, your relationship with fairness, balance, and truth is most personal.' },

    { id: 'major-12', name: 'The Hanged Man', up: 'Surrender as strategy. The Hanged Man doesn\'t struggle — he hangs willingly, seeing the world from a perspective no one else has access to. This is not passivity; it\'s the deepest form of patience.', rev: 'Stalling, martyrdom, or the refusal to surrender when surrender is the only wise move. You\'re either stuck because you won\'t let go, or you\'re sacrificing yourself for something that isn\'t worth it.', kUp: ['surrender','new perspective','letting go','suspension','sacrifice','patience'], kRev: ['stalling','martyrdom','resistance','needless sacrifice','stagnation','delays'], el: 'water' as const, planet: 'Neptune', heb: 'Mem', num: 12, path: 'Geburah to Hod', chart: 'Neptune in your chart resonates with The Hanged Man. Where Neptune sits natally, your capacity for surrender, transcendence, and seeing beyond the obvious is strongest.' },

    { id: 'major-13', name: 'Death', up: 'Transformation so complete that the old form cannot survive. Death is not the end — it is the necessary clearing that makes space for what comes next. The thing that is dying has served its purpose.', rev: 'Resistance to necessary transformation, fear of endings, or a transition that has stalled. You\'re holding onto something that needs to die — a relationship, an identity, a way of being — and the refusal is creating suffering.', kUp: ['transformation','endings','change','release','transition','rebirth','letting go'], kRev: ['resistance to change','stagnation','decay','fear of ending','prolonged suffering','holding on'], el: 'water' as const, zod: 'Scorpio', heb: 'Nun', num: 13, path: 'Tiphareth to Netzach', chart: 'Scorpio in your chart is activated by Death. Where Pluto and Scorpio sit natally, your capacity for profound transformation and regeneration runs deepest.' },

    { id: 'major-14', name: 'Temperance', up: 'Integration, balance, and the patient blending of opposing forces into something new. Temperance is the alchemist — not dramatic transformation but gradual, skilled synthesis. The middle path, walked with grace.', rev: 'Imbalance, excess, or the inability to find middle ground. You\'re lurching between extremes instead of finding the synthesis. Impatience is destroying what patience would create.', kUp: ['balance','moderation','patience','purpose','harmony','integration','alchemy'], kRev: ['imbalance','excess','lack of harmony','misalignment','impatience','overindulgence'], el: 'fire' as const, zod: 'Sagittarius', heb: 'Samekh', num: 14, path: 'Tiphareth to Yesod', chart: 'Sagittarius in your chart resonates with Temperance. Where Jupiter and Sagittarius sit, your capacity for philosophical balance and purposeful integration is active.' },

    { id: 'major-15', name: 'The Devil', up: 'Bondage to illusion, addiction, or shadow aspects of the self. The Devil doesn\'t chain you — you chain yourself. The card asks: what are you enslaved to, and do you realize the chains are unlocked?', rev: 'Breaking free from addiction, releasing shadow patterns, or the beginning of liberation from what has held you captive. The light switch in a dark room.', kUp: ['shadow','bondage','addiction','materialism','temptation','illusion','attachment'], kRev: ['liberation','breaking free','reclaiming power','detachment','releasing','shadow work'], el: 'earth' as const, zod: 'Capricorn', heb: 'Ayin', num: 15, path: 'Tiphareth to Hod', chart: 'Capricorn in your chart is activated by The Devil. Where Saturn and Capricorn sit natally, your shadow material — ambition tipping into obsession, discipline into rigidity — is most concentrated.' },

    { id: 'major-16', name: 'The Tower', up: 'Sudden destruction of false structures. The Tower falls because it was built on a lie — the collapse is violent but necessary. What replaces it will be built on truth. This is liberation through shock.', rev: 'Avoiding necessary destruction, prolonging a collapse, or the aftermath of a crisis. Either you\'re delaying an inevitable reckoning, or you\'re in the rubble wondering what to salvage.', kUp: ['upheaval','revelation','sudden change','destruction','liberation','awakening','crisis'], kRev: ['avoidance','fear of change','delayed disaster','aftermath','rebuilding','resistance'], el: 'fire' as const, planet: 'Mars', heb: 'Pe', num: 16, path: 'Netzach to Hod', chart: 'Mars in your chart is activated by The Tower. Where Mars sits natally, the potential for sudden, transformative disruption is strongest.' },

    { id: 'major-17', name: 'The Star', up: 'Hope, healing, and the calm after the storm. After The Tower\'s destruction, The Star pours living water onto the scorched earth. Renewal is possible. Faith — not in a system, but in life itself — is restored.', rev: 'Despair, loss of faith, or disconnection from hope. The light at the end of the tunnel has gone out — or you\'ve stopped looking for it.', kUp: ['hope','inspiration','renewal','serenity','faith','healing','purpose'], kRev: ['despair','disconnection','lack of faith','discouragement','hopelessness','creative block'], el: 'air' as const, zod: 'Aquarius', heb: 'Tzaddi', num: 17, path: 'Netzach to Yesod', chart: 'Aquarius in your chart resonates with The Star. Where Uranus and Aquarius sit natally, your capacity for visionary hope and humanitarian faith is strongest.' },

    { id: 'major-18', name: 'The Moon', up: 'Illusion, fear, and the journey through the dark. The Moon illuminates just enough to reveal shapes without defining them. Nothing is what it seems. The path forward requires trusting the process even when you can\'t see clearly.', rev: 'Clarity emerging from confusion, confronting fears, or releasing illusions. The fog is lifting. What was distorted is becoming clear.', kUp: ['illusion','fear','subconscious','anxiety','intuition','shadow','confusion'], kRev: ['clarity','releasing fear','truth emerging','facing shadow','overcoming anxiety','revelation'], el: 'water' as const, zod: 'Pisces', heb: 'Qoph', num: 18, path: 'Netzach to Malkuth', chart: 'Pisces in your chart is activated by The Moon. Where Neptune and Pisces sit natally, your experience of illusion, intuition, and the boundary between real and imagined is most intense.' },

    { id: 'major-19', name: 'The Sun', up: 'Joy, vitality, success, and the uncomplicated warmth of things going well. The Sun is the most unambiguously positive card in the deck — clarity, energy, and the simple pleasure of being alive.', rev: 'Diminished joy, temporary setbacks, or the inability to enjoy what\'s going well. The sun is behind a cloud — it\'s still there, but you can\'t feel it.', kUp: ['joy','success','vitality','clarity','optimism','warmth','celebration'], kRev: ['temporary sadness','inner child wounded','lack of clarity','diminished joy','setback','overexposure'], el: 'fire' as const, planet: 'Sun', heb: 'Resh', num: 19, path: 'Hod to Yesod', chart: 'The Sun activates your natal Sun placement. Where your Sun sign sits, your core vitality and self-expression shine most brightly.' },

    { id: 'major-20', name: 'Judgement', up: 'Resurrection, reckoning, and the call to become who you were always meant to be. The trumpet sounds and the dead rise — not literally, but the parts of yourself you\'d buried are being called back to life.', rev: 'Refusal to heed the call, self-doubt about your purpose, or harsh self-judgment that prevents transformation. The trumpet is sounding but you\'re pretending not to hear it.', kUp: ['judgement','rebirth','calling','reckoning','purpose','absolution','inner calling'], kRev: ['self-doubt','refusal','harsh self-criticism','ignoring the call','stagnation','unforgiveness'], el: 'fire' as const, planet: 'Pluto', heb: 'Shin', num: 20, path: 'Hod to Malkuth', chart: 'Pluto in your chart resonates with Judgement. Where Pluto sits natally, the call to profound transformation and the reckoning with your deepest truth is most active.' },

    { id: 'major-21', name: 'The World', up: 'Completion, integration, and the successful end of a major cycle. The World is the dancer at the center of the cosmos — everything in balance, the journey complete, the lesson learned. Wholeness.', rev: 'Incompletion, the final step not yet taken, or the bittersweet feeling of finishing something that defined you. The cycle is almost complete but something remains unresolved.', kUp: ['completion','integration','accomplishment','wholeness','travel','fulfillment','closure'], kRev: ['incompletion','delays','shortcuts','lack of closure','unfinished business','almost there'], el: 'earth' as const, planet: 'Saturn', heb: 'Tav', num: 21, path: 'Yesod to Malkuth', chart: 'Saturn in your chart is activated by The World. Where Saturn sits natally, the lessons of mastery, completion, and earned accomplishment are most personal.' },
  ].map(c => ({
    cardId: c.id,
    cardName: c.name,
    coreMeaning: { upright: c.up, reversed: c.rev },
    keywords: { upright: c.kUp, reversed: c.kRev },
    domains: {
      love: domainFrom(c.up, c.rev, '', ''),
      career: domainFrom(c.up, c.rev, '', ''),
      spiritual: domainFrom(c.up, c.rev, '', ''),
      health: domainFrom(c.up, c.rev, '', ''),
      creative: domainFrom(c.up, c.rev, '', ''),
      financial: domainFrom(c.up, c.rev, '', ''),
      family: domainFrom(c.up, c.rev, '', ''),
      self: domainFrom(c.up, c.rev, '', ''),
      general: domainFrom(c.up, c.rev, '', '')
    },
    positions: {
      situation: { positionKey: 'situation', frame: c.up.split('.')[0] + '.', emphasis: c.kUp[0] },
      advice: { positionKey: 'advice', frame: `Consider the energy of ${c.name}.`, emphasis: c.kUp[1] || c.kUp[0] },
      outcome: { positionKey: 'outcome', frame: `This leads toward ${c.kUp[0]}.`, emphasis: c.kUp[0] },
    },
    emotionalModifiers: {},
    interactions: [],
    fieldResponses: { positiveHigh: `Positive field amplifies ${c.name}'s upright themes.`, positiveMild: `Gentle support for ${c.kUp[0]}.`, neutral: `Balanced field. ${c.name} reads at standard strength.`, negativeMild: `Mild resistance. ${c.name}'s shadow themes may surface.`, negativeHigh: `Strong field tension. ${c.name}'s reversed aspects may dominate even in upright position.` },
    correspondences: { element: c.el, zodiac: c.zod, planet: c.planet, hebrewLetter: c.heb, numerology: c.num, treeOfLifePath: c.path, birthChartResonance: c.chart || '' }
  } as CardKnowledge))
];
